services:
  dispatcher:
    build: ./dispatcher
    ports:
      - "8002:8002"
    depends_on:
      - product_service
      - auth_service
      - order_service
      - mongo
    networks:
      - internal

  product_service:
    build: ./product_service
    expose:
      - "8000"
    networks:
      - internal

  auth_service:
    build: ./auth_service
    expose:
      - "8001"
    networks:
      - internal

  order_service:
    build: ./order_service
    expose:
      - "8003"
    networks:
      - internal

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  mongo_data: